apiVersion: v1
kind: Service
metadata:
  name: controlcenter-nodeport
  namespace: confluent
spec:
  type: NodePort
  selector:
    app: controlcenter
  ports:
    - port: 9021
      targetPort: 9021
      nodePort: 32000

